import Layout from "@/components/layout/layout";
import React from "react";
import CashHistory from "@/components/cash-history";

const CashHistoryPage = () => {
  return (
    <Layout title="Cash History" description="Generated by create next app">
      <CashHistory />
    </Layout>
  );
};

export default CashHistoryPage;
