import Deposit from "@/components/wallet/deposit";
import Layout from "@/components/layout/layout";
import React from "react";
import { getDataCollectionSnapshort } from "@/lib/snapshort-func";
import { setBettingRules } from "@/store/slices/bettingRulesSlice";
import { useAppDispatch } from "@/store/hook";

interface IPropsData {}

interface ComponentDepositPage extends React.FC<IPropsData> {}

const DepositPage: ComponentDepositPage = () => {
  const dispatch = useAppDispatch();

  React.useEffect(() => {
    getDataCollectionSnapshort("preferences", (data) =>
      dispatch(setBettingRules({ rules: data.data[0] }))
    );
  }, []);
  return (
    <Layout title="Deposit" description="Generated by create next app">
      <Deposit />
    </Layout>
  );
};
export default DepositPage;
