import React from "react";
import Categories from "@/components/categories";
import Layout from "@/components/layout/layout";
import Minigame from "@/components/mini-game";

// const Categories = React.lazy(() => import("@/components/categories"));
// const Layout = React.lazy(() => import("@/components/layout/layout"));
// const MiniGame = React.lazy(() => import("@/components/mini-game"));
const MiniGamePage = () => {
  return (
    <Layout title="Mini Game" description="Generated by create next app">
      <div style={{ lineHeight: 0, marginBottom: 50 }}>
        <Categories title="미니게임" isShowLogoRight />
        <p>총 11개의 미니게임이 준비되어 있습니다.</p>
      </div>
      <Minigame />
    </Layout>
  );
};

export default MiniGamePage;
