import Layout from '@/components/layout/layout'
import NoticeList from '@/components/ListNoice/ListNoice'
import React from 'react'

const Announcement = () => {
    return <Layout title="Notice" description="Generated by create next app">
        <NoticeList title='Event' />
    </Layout>
}

export default Announcement