import React from "react";
import Layout from "@/components/layout/layout";
import Withdraw from "@/components/wallet/withdraw";
// const Layout = React.lazy(() => import('@/components/layout/layout'))
// const Withdraw = React.lazy(() => import('@/components/wallet/withdraw'))
import { getDataCollectionSnapshort } from "@/lib/snapshort-func";
import { setBettingRules } from "@/store/slices/bettingRulesSlice";
import { useAppDispatch } from "@/store/hook";

interface IPropsData {}

interface ComponentWithdrawPage extends React.FC<IPropsData> {}

const WithdrawPage: ComponentWithdrawPage = () => {
  const dispatch = useAppDispatch();

  React.useEffect(() => {
    getDataCollectionSnapshort("preferences", (data) =>
      dispatch(setBettingRules({ rules: data.data[0] }))
    );
  }, []);
  return (
    <Layout title="Withdraw" description="Generated by create next app">
      <Withdraw />
    </Layout>
  );
};

export default WithdrawPage;
