import Casino from "@/components/casino";
import Layout from "@/components/layout/layout";
import React from "react";

const CasinoPage = () => {
  return (
    <Layout title="Casino" description="Generated by create next app">
      <Casino />
    </Layout>
  );
};

export default CasinoPage;
