import Categories from "@/components/categories";
import Layout from "@/components/layout/layout";
import Virtual from "@/components/virtual";
import React from "react";

// const Categories = React.lazy(() => import("@/components/categories"));
// const Layout = React.lazy(() => import("@/components/layout/layout"));
// const Virtual = React.lazy(() => import("@/components/virtual"));

const VirtualPage = () => {
  return (
    <Layout title="Mini game" description="Generated by create next app">
      <Virtual />
    </Layout>
  );
};

export default VirtualPage;
