import React from "react";
import Categories from "@/components/categories";
import Layout from "@/components/layout/layout";
import SlotGame from "@/components/slot-game";
import { slotProviderList } from "@/data";
import { useRouter } from "next/router";

const SlotGamePage = () => {
  const router = useRouter();
  const { slugProvider } = router.query;

  const handleChooseProvider = (id: string) => {
    router.push(`/slot-provider/${id}/slot-game`);
  };

  return (
    <Layout title="Slot Game" description="Generated by create next app">
      <div style={{ lineHeight: 0, marginBottom: 20 }}>
        <Categories title="슬롯게임" isShowLogoRight />
        <p>공정성과 재미가 보장되는 1000여가지 메이저 슬롯게임</p>
      </div>
      <div
        style={{
          lineHeight: 0,
          marginBottom: 50,
          display: "grid",
          gridTemplateColumns: `repeat(auto-fit,100px)`,
          gap: 5,
          justifyContent: "center",
        }}
      >
        {slotProviderList.map((i) => (
          <div
            key={i.id}
            style={{
              display: "flex",
              flexDirection: "column",
              gap: 10,
              justifyContent: "center",
              height: 80,
              padding: "5px 20px",
              background:
                slugProvider![0] === i.id
                  ? "var(--color-blue)"
                  : "var(--color-grey-800)",
              borderRadius: 5,
              cursor: "pointer",
            }}
            onClick={() => {
              handleChooseProvider(i.id);
            }}
          >
            <img src={i.provider_logo} alt={i.provider_logo} />
            <p>{i.name}</p>
          </div>
        ))}
      </div>
      <SlotGame />
    </Layout>
  );
};

export default SlotGamePage;
