import React from "react";
import Layout from "@/components/layout/layout";
// const Layout = React.lazy(() => import('@/components/layout/layout'))
// const Withdraw = React.lazy(() => import('@/components/wallet/withdraw'))
import CustomerService from "@/components/CustomerService";

interface IPropsData {}

interface ComponentService extends React.FC<IPropsData> {}

const Service: ComponentService = () => {
  return (
    <Layout title="Customer Service" description="Generated by create next app">
      <CustomerService />
    </Layout>
  );
};

export default Service;
