import Head from "next/head";
import React from "react";
import FormUI from "@/components/ui/form";
import { useRouter } from "next/router";
import { useAppSelector } from "@/store/hook";
import { isEmpty } from "lodash";

const Home: React.FC = () => {
  const [isRedirecting, setIsRedirecting] = React.useState(false);
  const token = useAppSelector((state) => state.token);
  const router = useRouter();

  React.useEffect(() => {
    if (token.access_token) {
      setIsRedirecting(true);
      router.push(
        {
          pathname: "/sports",
          query: { loginFormat: "signIn" },
        },
        "/sports"
      );
    }
  }, [token, isRedirecting, router]);

  return (
    <>
      <Head>
        <title>Sport Betting</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logos/danang_favicon.svg" />
      </Head>
      <FormUI />
    </>
  );
};
export default Home;
