import * as React from "react";
import Layout from "@/components/layout/layout";
import Table from "@/components/history/Table";
import type { NextPage } from "next";
import { useAppSelector } from "@/store/hook";
import { queryBuilderFunc } from "@/lib/query-func";
import useSWR from "swr";

import { db } from "@/helpers/db-config";
import { DocumentData } from "@firebase/firestore-types";
import {
  collection,
  query,
  where,
  onSnapshot,
  orderBy,
} from "firebase/firestore";
import EmptyData from "@/components/ui/EmptyData/input";
import { isEmpty } from "lodash";

export interface IResponseData {
  amount: number;
  betting: IBetting[];
  bonus: number;
  id: string;
  status: string;
  time: string;
  total_odds: string;
  user_id: string;
  result: string;
  winning_amount: number;
  delete: boolean;
  created_at: number;
}

interface IBetting {
  away_team: string;
  home_team: string;
  league: string;
  match_status: string;
  odd: { odds: string; name: string; id: string };
  odd_type: string;
  score: null;
  bet_result: string;
  sport_id: string;
}

const History: NextPage = () => {
  const { id: userID } = useAppSelector((state) => state.user);
  const [dataHistory, setDataHistory] = React.useState<DocumentData>([]);

  const { data, mutate } = useSWR("history" + userID, {
    fetcher: async () => {
      const q = query(
        collection(db, "bets"),
        where("user_id", "==", userID),
        where("delete", "==", false),
        orderBy("created_at", "desc")
      );

      onSnapshot(q, (snapshots: any) => {
        const data: DocumentData[] = [];
        snapshots.forEach((doc: any) => {
          data.push(doc.data());
        });
        setDataHistory(data);
      });
    },
  });

  return (
    <Layout title="BestHistory" description="Generated by create next app">
      {!isEmpty(dataHistory) ? (
        <Table data={dataHistory} />
      ) : (
        <div
          style={{
            display: "flex",
            justifyContent: "center",
            height: "100%",
            margin: "0 auto",
            alignItems: "center",
            gap: 5,
          }}
        >
          <EmptyData />
        </div>
      )}
    </Layout>
  );
};

export default History;
